---
# vars file for launchEC2

# set these parameters to control the region, keypair, and AMI that are launched
ec2_region: sa-east-1
instances_keypair: api
image_id: ami-466b132a

# security groups to be created
security_groups:
  - name: ssh
    desc: ssh security group
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  - name: http
    desc: port 80 security group
    rules:
      - proto: tcp
        from_port: "80"
        to_port: "80"
        cidr_ip: 0.0.0.0/0

# Instances to launch be launched.
# If you re-run the playbook after modifying exact_count,
# instances will be terminated if the actual count > exact_count,
# or new instances will be launched if actual count < exact_count.

ec2_instances:

  - instance_type: t2.micro
    image: "{{ image_id }}"
    keypair: "{{instances_keypair}}"
    group: ['http', 'ssh']
    instance_tags:
        Name: python_api
    exact_count: 1
    count_tag:
        Name: python_api

ec2_access_key: AKIAIKNLEQ3ZFM3VILBA
ec2_secret_key: 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
