---
# tasks file for installPython
- name: Enforces that python in installed on Debian distros
  raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
  register: output
  changed_when: output.stdout != ""
