---
# tasks file for flaskapp
- name: Install pip
  apt:
    name: python
    state: present

- name: Install apache2 wsgi flask module
  apt:
    name: libapache2-mod-wsgi
    state: present

- name: Install virtualenv
  apt:
    name: virtualenv
    state: present

- name: Copy requirements.txt for virtualenv
  copy:
    src: files/requirements.txt
    dest: /home/ubuntu/requirements.txt

- name: Create virtualenv and install modules
  pip:
    virtualenv: /var/www/FlaskApi/FlaskApi/flaskapi
    virtualenv_python: python2.7
    requirements: /home/ubuntu/requirements.txt

- name: Configure FlaskApi virtualhost
  copy: src=FlaskApi.conf dest=/etc/apache2/sites-available/FlaskApi.conf
  notify: apache2 restart

- name: Enable FlaskApi virtualhost
  shell: a2ensite FlaskApi
  notify: apache2 restart

- name: Update FlaskApi virtualhost with Server's IP
  shell: ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) && sed -i -e "s/ServerName .*/ServerName $ip/g" /etc/apache2/sites-enabled/FlaskApi.conf
  notify: apache2 restart

- name: Check __init__.py exists
  stat: path=/var/www/FlaskApi/FlaskApi/__init__.py
  register: FlaskApi

- name: Create FlaskApi structure
  copy: src=FlaskApi dest=/var/www/
  when: FlaskApi.stat.exists == False
  notify: apache2 restart
